apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "secrets"
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  refreshInterval: 10m
  target:
    name: env
  dataFrom:
  - extract:
      key: myapp/{{ .Values.deployment.env }}  


