apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.deployment.name }}-ingress"
  annotations:
   #  alb.ingress.kubernetes.io/group.order: "10"
   #  alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
   #  alb.ingress.kubernetes.io/healthcheck-path: /
   #  alb.ingress.kubernetes.io/healty-threshold-count: "1"
   #  alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 443},{"HTTP": 80}]'
     #alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
   #  alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
    # kubernetes.io/ingress.class: alb 
     kubernetes.io/ingress.class: nginx
     #alb.ingress.kubernetes.io/scheme: internet-facing 
 #    cert-manager.io/cluster-issuer: awspca-issuer
     cert-manager.io/cluster-issuer: acme-issuer
spec:
  rules:
    {{- if eq .Values.deployment.env "prod" }}
  - host: "nikvak.com"
    {{- else  }}
  - host: "{{ .Values.deployment.env }}.nikvak.com"
    {{ end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.deployment.name }}-svc"
            port:
              number: {{ .Values.deployment.port }}
  tls:
  - hosts:
    {{- if eq .Values.deployment.env "prod" }}
    - "nikvak.com"
    {{- else }}
    - "{{ .Values.deployment.env }}.nikvak.com"
    {{ end }}
    secretName: myingress-cert
