apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "ingress"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: acme-issuer
spec:
  rules:
      {{ if eq .Values.deployment.env "prod" }}
    - host: "daguaniko.com"
      {{ else }}
    - host: "{{.Values.deployment.env}}.daguaniko.com"
      {{ end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.deployment.name }}-svc"
                port:
                  number: {{ .Values.deployment.port }}
  tls:
  - hosts:
    {{ if eq .Values.deployment.env "prod" }}
    - "daguaniko.com"
    {{ else }}
    - "{{ .Values.deployment.env }}.daguaniko.com"
    {{ end }}
    secretName: myingress-cert
